name: Publish Docker image

on:
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    # 用于配置当前workflow的参数
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      # checkout
      - name: Check out the repo
        uses: actions/checkout@v2

      # 在当前操作系统安装node
      # vitepress build
      - name: Build VitePress with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm run docs:build

      # login
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # build docker image
      # - name: Build the Docker image
      #   run: |
      #     docker build . --file Dockerfile --tag kevin031/blog-vitepress:latest
      #     docker push kevin031/blog-vitepress:latest

      # - name: Execute SSH commmands on remote server
      #   uses: JimCronqvist/action-ssh@master
      #   with:
      #     hosts: ${{ secrets.HOST }}
      #     privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
      #     debug: true
      #     command: |
      #       docker ps -a
      #       docker rm -f blog-vitepress
      #       docker pull kevin031/blog-vitepress
      #       docker run --name blog-vitepress --restart unless-stopped -p 20231:80 -d kevin031/blog-vitepress

      # 资源直接部署到服务器
      - name: Deploy to Staging My server
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "docs/.vitepress/dist/"
          REMOTE_HOST: ${{ secrets.HOST }} #服务器ip
          REMOTE_USER: "root"
          TARGET: "/www/wwwroot/vitepress.kevinlau.cn/"
          EXCLUDE: "/node_modules/"
