name: Publish Docker image

on:
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    # 用于配置当前workflow的参数
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      # checkout
      - name: Check out the repo
        uses: actions/checkout@v2

      # 在当前操作系统安装node
      # vitepress build
      - name: Build VitePress with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run docs:build

      # build docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag kevin031/blog-vitepress:latest

      # login
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # push to docker hub
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kevin031/blog-vitepress:latest

      # - name: Execute SSH commmands on remote server
      #   uses: JimCronqvist/action-ssh@master
      #   with:
      #     hosts: ${{ secrets.HOST }}
      #     privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
      #     debug: true
      #     command: |
      #       docker ps -a
      #       docker rm -f kevinlau-cn
      #       docker pull kevin031/blog-vitepress
      #       docker run --name kevinlau-cn --restart unless-stopped -p 20229:80 -d kevin031/blog-vitepress
