name: Publish By SSH

on:
  push:
    branches:
      - master
      - record
jobs:
  push_to_registry:
    name: Build and Push
    runs-on: ubuntu-latest
    # 用于配置当前workflow的参数
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      # checkout
      - name: Check out the repo
        uses: actions/checkout@v2

      # 在当前操作系统安装node
      # vitepress build
      - name: Build VitePress with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm run docs:build

      # 资源直接部署到服务器
      # 部署到 master 分支的服务器路径
      - name: Deploy to Server Production Path
        if: github.ref == 'refs/heads/master'
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-rltgoDzvO'
          SOURCE: 'docs/.vitepress/dist/'
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: 'root'
          TARGET: '/www/wwwroot/blog.kevinlau.cn/'
          EXCLUDE: '/node_modules/'

      # 部署到 record 分支的服务器路径
      - name: Deploy to Server Record Path
        if: github.ref == 'refs/heads/record'
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-rltgoDzvO'
          SOURCE: 'docs/.vitepress/dist/'
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: 'root'
          TARGET: '/www/wwwroot/kevinlau.cn/'
          EXCLUDE: '/node_modules/'
